//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService_PS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountType()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<double> MaxOfMoney { get; set; }
        public Nullable<double> WithDrawMin { get; set; }
        public Nullable<double> WithDrawMax { get; set; }
        public Nullable<double> MaxOfTimesForDay { get; set; }
        public Nullable<System.DateTime> FlagDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
